services:
  - type: web
    name: little-kitten-chat
    env: python
    plan: free
    runtime: python 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
